name = "PowerModelsONM"
uuid = "25264005-a304-4053-a338-565045d392ac"
authors = ["David M Fobes <dfobes@lanl.gov>"]
version = "3.4.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PolyhedralRelaxations = "2e741578-48fa-11ea-2d62-b52c946f73a0"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PowerModelsProtection = "719c1aef-945b-435a-a240-4c2992e5e0df"
PowerModelsStability = "f9e4c324-c3b6-4bca-9c3d-419775f0bd17"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
ArgParse = "1.1"
Combinatorics = "1"
EzXML = "1.1.0"
Graphs = "1.4.1, 1.6, 1.7, 1.8, 1.9"
HiGHS = "1.5.2"
Hwloc = "2"
InfrastructureModels = "0.7"
Ipopt = "0.9, 1.0.2, 1.3"
JSON = "0.21"
JSONSchema = "0.3.3, 1"
JuMP = "0.22, 0.23, 1"
Juniper = "0.8, 0.9"
LoggingExtras = "0.4.7, 0.4.9"
PolyhedralRelaxations = "0.3.3, 0.3.4, 0.3.5"
PowerModelsDistribution = "0.14.4, 0.14.9, 0.15"
PowerModelsProtection = "0.5.2"
PowerModelsStability = "0.3.2"
Requires = "1.1.3, 1.3"
StatsBase = "0.33, 0.34"
julia = "1.6"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "HiGHS", "Ipopt", "JSON", "Juniper", "PowerModelsDistribution"]
